#!/usr/bin/env python
"""
Script to run solutions.
"""

import argparse
import sys
from datetime import date
from typing import List

from aoc.solver import solve, test

class Args(argparse.Namespace):
    """Namespace type for arguments."""

    year: int
    day: int
    part: List[int]
    test: bool
    submit: bool


def _get_args():
    """Parse the command line arguments."""
    latest = date.today()
    if latest.month != 12:
        latest.year -= 1
        latest.day = 25
    elif latest.day > 25:
        latest.day = 25

    parser = argparse.ArgumentParser()
    parser.add_argument("--year", "-y", type=int, default=latest.year)
    parser.add_argument("--day", "-d", type=int, default=latest.day)
    parser.add_argument("--part", "-p", type=int, nargs="*", default=[1, 2])

    action_group = parser.add_mutually_exclusive_group()
    action_group.add_argument("--test", "-t", action="store_true", default=False)
    action_group.add_argument("--submit", "-s", action="store_true", default=False)

    return parser.parse_args(namespace=Args())


def main() -> None:
    """Main routine."""
    args = _get_args()

    if not args.test:
        rc = solve(args.year, args.day, args.part, args.submit)
    else:
        rc = test(args.year, args.day, args.part)

    sys.exit(rc)


if __name__ == "__main__":
    main()
