#!/usr/bin/env python
"""
Script to run solutions.
"""

import argparse
import sys
from typing import List

from aocd.get import current_day, most_recent_year

from aoc.solver import solve, test


class Args(argparse.Namespace):
    """Namespace type for arguments."""

    year: int
    day: int
    part: List[int]
    test: bool
    submit: bool


def _get_args():
    """Parse the command line arguments."""
    latest_year = most_recent_year()
    latest_day = current_day()

    parser = argparse.ArgumentParser()
    parser.add_argument("--year", "-y", type=int, default=latest_year)
    parser.add_argument("--day", "-d", type=int, default=latest_day)
    parser.add_argument("--part", "-p", type=int, nargs="*", default=[1, 2])

    action_group = parser.add_mutually_exclusive_group()
    action_group.add_argument("--test", "-t", action="store_true", default=False)
    action_group.add_argument("--submit", "-s", action="store_true", default=False)

    return parser.parse_args(namespace=Args())


def main() -> None:
    """Main routine."""
    args = _get_args()

    if not args.test:
        rc = solve(args.year, args.day, args.part, args.submit)
    else:
        rc = test(args.year, args.day, args.part)

    sys.exit(rc)


if __name__ == "__main__":
    main()
